# Generated by Django 4.1 on 2022-12-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagonauto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suzuki',
            name='about',
            field=models.TextField(default='About'),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='boot_space',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='emission_norm',
            field=models.CharField(default='BS IV', max_length=64),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='engine_type',
            field=models.CharField(default='Type 0', max_length=64),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='fuel_type',
            field=models.CharField(default='P/D/C', max_length=64),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='gear_box',
            field=models.CharField(default='5 gears', max_length=64),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='max_power',
            field=models.CharField(default='0 @ 0rpm', max_length=64),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='max_torque',
            field=models.CharField(default='0 @ 0rpm', max_length=64),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='mileage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='no_cylinders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='others',
            field=models.TextField(default='Others'),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='seating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='tank_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='transmission_type',
            field=models.CharField(default='Automatic', max_length=64),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='valves_per_cylinder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suzuki',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suzuki',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
